### ISSUE TITLE
error w/ react-tap-event-plugin 0.1.7, meteor/react-packages

### ISSUE THREAD

**Issue by rkstar** [rkstar/meteor-material-ui-example#1]
this is the error that is thrown when i run `meteor`
from https://github.com/rkstar/meteor-material-ui-example/commit/089f02cc4654518fb3d0f89d8a8a6ce13ed28336

```
=> Started proxy.                             
=> Started MongoDB.                           

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'externalify' from '/Users/rkstar/dev/projects/mat/packages/npm-container/.npm/package'
  at /Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
  at process (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
  at ondir (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
  at load (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
  at /Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
  at Object.oncomplete (fs.js:108:15)
```

**Comment by rkstar** [comment]
see [README.md](https://github.com/rkstar/meteor-material-ui-example)
